# gazelle:python_root
# gazelle:python_default_visibility //:__subpackages__
# gazelle:python_ignore_files deploy.py
# gazelle:map_kind py_test pytest_test //bazel:pytest_test.bzl
# gazelle:exclude webhooks
# gazelle:exclude data-gen

load("@bazel_gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@pypi//:requirements.bzl", "all_whl_requirements")
load("@rules_python_gazelle_plugin//manifest:defs.bzl", "gazelle_python_manifest")
load("@rules_python_gazelle_plugin//modules_mapping:def.bzl", "modules_mapping")

exports_files(
    [
        "pyproject.toml",
        "requirements_bazel.txt",
        "uv.lock",
    ],
    visibility = ["//visibility:public"],
)

# keep
filegroup(
    name = "api_samples",
    srcs = glob(["api/samples/**/*.json"]),
    visibility = ["//tests:__subpackages__"],
)

# keep
filegroup(
    name = "webhook_handler_sources",
    srcs = glob(["webhooks/*.py"]),
    visibility = ["//tests:__subpackages__"],
)

# keep
filegroup(
    name = "webhook_export_to_attio_source",
    srcs = ["webhooks/export_to_attio.py"],
    visibility = ["//tests/scripts:__pkg__"],
)

# keep
filegroup(
    name = "github_workflow_sources",
    srcs = glob([
        ".github/workflows/**/*.Dockerfile",
        ".github/workflows/**/*.dockerignore",
        ".github/workflows/**/*.py",
        ".github/workflows/**/*.txt",
        ".github/workflows/**/*.yml",
    ]),
    visibility = ["//tests/workflows:__pkg__"],
)

modules_mapping(
    name = "modules_map",
    include_stub_packages = True,
    wheels = all_whl_requirements,
)

gazelle_python_manifest(
    name = "gazelle_python_manifest",
    modules_mapping = ":modules_map",
    pip_repository_name = "pypi",
    requirements = "//:requirements_bazel.txt",
)

gazelle_binary(
    name = "gazelle_python_binary",
    languages = ["@rules_python_gazelle_plugin//python"],
)

gazelle(
    name = "gazelle",
    gazelle = ":gazelle_python_binary",
)
