load("//bazel:pytest_test.bzl", "pytest_test")

pytest_test(
    name = "test_pytest_main",
    srcs = ["test_pytest_main.py"],
    pyi_deps = ["@pypi//pytest"],
    deps = ["//tests:conftest"],
)

pytest_test(
    name = "test_edge_facade",
    srcs = ["test_edge_facade.py"],
    deps = [
        "//src:edge",
        "//tests:conftest",
        "@pypi//pytest",
    ],
)
