"""Registry file schema + load/write helpers.

The registry is a gitignored YAML inventory of (source, handler) → Modal app
+ Hookdeck wiring. Generated by `cli/webhook/sync.py`; consumed by the `list`
command. Keep this module side-effect free — no API calls live here.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, ConfigDict


# Anchored on this file's path (not CWD) so `uv run python -m cli.main webhook list`
# resolves the same registry regardless of where the user invoked it from.
# cli/webhook/registry.py → repo root is parents[2].
REPO_ROOT: Path = Path(__file__).resolve().parents[2]
REGISTRY_PATH: Path = REPO_ROOT / "webhooks" / "registry.yaml"


class HandlerEntry(BaseModel):
    """One (model, handler) pair: the Modal app it expects + the Hookdeck wiring."""

    model_config = ConfigDict(extra="forbid")

    handler: str
    deployed: bool
    modal_app: str | None
    modal_url: str | None
    hookdeck_source_id: str | None
    hookdeck_destination_id: str | None
    hookdeck_connection_id: str | None


class SourceEntry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    source: str
    model: str
    handlers: list[HandlerEntry]


class SingletonEntry(BaseModel):
    """Source-agnostic Modal app (e.g. the dev raw-passthrough bucket)."""

    model_config = ConfigDict(extra="forbid")

    name: str
    deployed: bool
    modal_app: str
    modal_url: str | None
    hookdeck_source_id: str | None
    hookdeck_destination_id: str | None
    hookdeck_connection_id: str | None


class Registry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    generated_at: datetime
    webhooks: list[SourceEntry]
    singletons: list[SingletonEntry]


def write_registry(registry: Registry) -> None:
    REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload: dict[str, Any] = registry.model_dump(mode="json")
    REGISTRY_PATH.write_text(
        yaml.safe_dump(payload, sort_keys=False, default_flow_style=False),
    )


def load_registry() -> Registry:
    raw: dict[str, Any] = yaml.safe_load(REGISTRY_PATH.read_text())
    return Registry.model_validate(raw)
