load("@rules_python//python:defs.bzl", "py_library")

# gazelle:python_generation_mode project

# keep
filegroup(
    name = "architecture_sources",
    srcs = glob(["**/*.py"]),
    visibility = ["//tests/architecture:__pkg__"],
)

py_library(
    name = "linkedin",
    srcs = [
        "__init__.py",
        "api_helpers.py",
        "member_data.py",
    ],
    pyi_deps = ["@pypi//types_requests"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//dlt",
        "@pypi//logfire",
        "@pypi//orjson",
        "@pypi//pydantic",
        "@pypi//requests",
    ],
)
