load("@rules_python//python:defs.bzl", "py_binary", "py_library")

# gazelle:python_generation_mode project

py_binary(
    name = "uv_resolve",
    srcs = ["uv_resolve.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "lib",
    srcs = [
        "__init__.py",
        "container.py",
        "env.py",
        "flox.py",
        "uv_bootstrap.py",
        "uv_resolve.py",
    ],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//dagger_io"],
)
