load("//bazel:pytest_test.bzl", "pytest_test")

pytest_test(
    name = "test_bazel_dagger_workflow",
    srcs = ["test_bazel_dagger_workflow.py"],
    data = ["//:github_workflow_sources"],  # keep
    pyi_deps = ["@pypi//types_pyyaml"],
    deps = [
        "//tests:conftest",
        "@pypi//pytest",
        "@pypi//pyyaml",
    ],
)

pytest_test(
    name = "test_integration_workflow",
    srcs = ["test_integration_workflow.py"],
    data = [
        "//:flox_manifest_sources",
        "//:github_workflow_sources",
    ],  # keep
    pyi_deps = ["@pypi//types_pyyaml"],
    deps = [
        "//tests:conftest",
        "@pypi//pytest",
        "@pypi//pyyaml",
    ],
)

pytest_test(
    name = "test_triage_workflow",
    srcs = ["test_triage_workflow.py"],
    data = [
        "//:github_workflow_sources",
        "//:pyproject.toml",
        "//scripts:workflow_test_script_sources",
    ],  # keep
    pyi_deps = ["@pypi//types_pyyaml"],
    deps = [
        "//tests:conftest",
        "@pypi//pytest",
        "@pypi//pyyaml",
    ],
)
