load("@rules_python//python:defs.bzl", "py_binary", "py_library")

# keep
filegroup(
    name = "workflow_ci_sources",
    srcs = glob([
        "*.py",
        "constraints/*.txt",
    ]),
    visibility = ["//:__pkg__"],
)

py_binary(
    name = "bazel_dagger",
    srcs = ["bazel_dagger.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//anyio",
        "@pypi//dagger_io",
    ],
)

py_binary(
    name = "flox_image_dagger",
    srcs = ["flox_image_dagger.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//anyio",
        "@pypi//dagger_io",
    ],
)

py_binary(
    name = "pytest_dependency_image_publish",
    srcs = ["pytest_dependency_image_publish.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":pytest_dependency_image",
        "@pypi//anyio",
        "@pypi//dagger_io",
    ],
)

py_binary(
    name = "pytest_integration_dagger",
    srcs = ["pytest_integration_dagger.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":pytest_dependency_image",
        "@pypi//anyio",
        "@pypi//dagger_io",
    ],
)

py_library(
    name = "pytest_dependency_image",
    srcs = ["pytest_dependency_image.py"],
    visibility = ["//:__subpackages__"],
    deps = ["@pypi//dagger_io"],
)

py_binary(
    name = "triage_dagger",
    srcs = ["triage_dagger.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//anyio",
        "@pypi//dagger_io",
    ],
)

py_binary(
    name = "triage_diagnose_dagger",
    srcs = ["triage_diagnose_dagger.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//anyio",
        "@pypi//dagger_io",
    ],
)

py_library(
    name = "ci",
    srcs = [
        "bazel_dagger.py",
        "flox_image_dagger.py",
        "pytest_dependency_image.py",
        "pytest_dependency_image_publish.py",
        "pytest_integration_dagger.py",
        "triage_dagger.py",
        "triage_diagnose_dagger.py",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "@pypi//anyio",
        "@pypi//dagger_io",
    ],
)
