#!/usr/bin/env -S uv run python
"""Generate the docs-site CLI reference from the Typer app tree.

Emits one Mintlify MDX page per `gtm` subapp into ``docs/cli/`` by walking the
click command tree behind ``cli.main.app``. The Typer ``help=`` strings are the
single source of truth: improving the reference means improving ``--help`` in
``cli/`` and regenerating — never editing the generated pages by hand.

Why generated: hand-written CLI inventories in this repo rot within weeks
(the README's tree omitted three subapps by launch day). CI runs ``--check``
so a CLI surface change that skips regeneration fails the build.

Usage::

    uv run scripts/docs-cli_reference-generate.py            # write pages
    uv run scripts/docs-cli_reference-generate.py --check    # CI drift gate

``--check`` regenerates in memory and exits 1 if any page differs from disk,
if a generated page is missing from docs.json navigation, or if a stale
non-generated page lingers in ``docs/cli/`` (``index.mdx`` is hand-written
and exempt).

Optional hand-written examples: if ``docs/snippets/cli/<subapp>-examples.mdx``
exists, the generated page imports and renders it under an Examples heading.
Snippets are curated by hand; the generator only wires them in.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

import click
import typer.main

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"
DOCS_CLI_DIR = DOCS_DIR / "cli"
DOCS_JSON = DOCS_DIR / "docs.json"
SNIPPETS_DIR = DOCS_DIR / "snippets" / "cli"

BANNER = (
    "{/* AUTOGENERATED by scripts/docs-cli_reference-generate.py — do not edit."
    " Edit the help= strings in cli/ and rerun:"
    " uv run scripts/docs-cli_reference-generate.py */}"
)

# Pages in docs/cli/ that are hand-written and never touched by the generator.
HAND_WRITTEN = {"index.mdx"}


def _mdx_escape(text: str) -> str:
    """Escape characters MDX would interpret as JSX/expressions in prose."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
    )


def _cell(text: str) -> str:
    """Escape a Markdown table cell (pipes would split the row)."""
    return _mdx_escape(text).replace("|", "&#124;").replace("\n", " ").strip()


def _default_repr(param: click.Parameter) -> str:
    if param.required or param.default is None:
        return "—"
    if callable(param.default):
        return "dynamic"
    if isinstance(param.default, bool):
        return f"`{str(param.default).lower()}`"
    if param.default == "":
        return '`""`'
    return f"`{param.default}`"


def _command_section(path: list[str], cmd: click.Command) -> str:
    full = " ".join(["gtm", *path])
    lines: list[str] = [f"### `{full}`", ""]

    if cmd.help:
        lines.append(_mdx_escape(cmd.help.strip()))
        lines.append("")

    ctx = click.Context(cmd, info_name=full)
    usage = cmd.get_usage(ctx).removeprefix("Usage: ").strip()
    lines.extend(["```bash", f"uv run {usage}", "```", ""])

    arguments = [p for p in cmd.params if isinstance(p, click.Argument)]
    options = [
        p for p in cmd.params if isinstance(p, click.Option) and "--help" not in p.opts
    ]

    if arguments:
        lines.extend(
            [
                "| Argument | Type | Required |",
                "| --- | --- | --- |",
            ],
        )
        lines.extend(
            f"| `{(arg.metavar or arg.name or '').upper()}` "
            f"| {_cell(arg.type.name)} "
            f"| {'yes' if arg.required else 'no'} |"
            for arg in arguments
        )
        lines.append("")

    if options:
        lines.extend(
            [
                "| Option | Type | Default | Description |",
                "| --- | --- | --- | --- |",
            ],
        )
        for opt in options:
            names = ", ".join([*opt.opts, *opt.secondary_opts])
            lines.append(
                f"| `{names}` "
                f"| {_cell(opt.type.name)} "
                f"| {_default_repr(opt)} "
                f"| {_cell(opt.help or '')} |",
            )
        lines.append("")

    if any("--apply" in p.opts for p in cmd.params if isinstance(p, click.Option)):
        lines.extend(
            [
                "<Warning>",
                "  Preview by default: without `--apply` this command prints the"
                " planned mutation and writes nothing. See the"
                " [CLI contract](/concepts/cli-contract).",
                "</Warning>",
                "",
            ],
        )
    return "\n".join(lines)


def _leaf_commands(group: click.Group) -> list[tuple[str, click.Command]]:
    return [
        (name, cmd)
        for name, cmd in group.commands.items()
        if not isinstance(cmd, click.Group)
    ]


def _child_groups(group: click.Group) -> list[tuple[str, click.Group]]:
    return [
        (name, cmd)
        for name, cmd in group.commands.items()
        if isinstance(cmd, click.Group)
    ]


def _subapp_page(name: str, group: click.Group) -> str:
    summary = (group.help or group.short_help or "").strip().rstrip(".")
    description = f"Command reference for gtm {name}"
    if summary:
        description += f" — {summary}"
    description += ". Generated from the CLI help text."

    parts: list[str] = [
        "---",
        f'title: "gtm {name}"',
        f'description: "{description}"',
        "---",
        "",
        BANNER,
        "",
    ]

    if summary:
        parts.extend([f"{_mdx_escape(summary)}.", ""])
    parts.extend(
        [
            "Every command follows the [CLI contract](/concepts/cli-contract):"
            " JSON on stdout, errors on stderr, and command-specific mutation"
            " safety controls. Keys resolve as described in"
            " [Secrets and API keys](/secrets).",
            "",
        ],
    )

    snippet = SNIPPETS_DIR / f"{name}-examples.mdx"
    if snippet.exists():
        parts.extend(
            [
                f"import CliExamples from '/snippets/cli/{name}-examples.mdx';",
                "",
                "## Examples",
                "",
                "<CliExamples />",
                "",
            ],
        )

    leaves = _leaf_commands(group)
    if leaves:
        parts.extend(["## Commands", ""])
        parts.extend(
            _command_section([name, leaf_name], cmd) for leaf_name, cmd in leaves
        )

    for child_name, child in _child_groups(group):
        child_help = (child.help or child.short_help or "").strip()
        parts.extend([f"## `gtm {name} {child_name}`", ""])
        if child_help:
            parts.extend([_mdx_escape(child_help), ""])
        parts.extend(
            _command_section([name, child_name, leaf_name], cmd)
            for leaf_name, cmd in _leaf_commands(child)
        )
        for grandchild_name, grandchild in _child_groups(child):
            parts.extend(
                _command_section(
                    [name, child_name, grandchild_name, leaf_name],
                    cmd,
                )
                for leaf_name, cmd in _leaf_commands(grandchild)
            )

    return "\n".join(parts).rstrip() + "\n"


def _generate() -> dict[str, str]:
    from cli.main import app  # deferred: imports the full project

    root = typer.main.get_command(app)
    if not isinstance(root, click.Group):  # pragma: no cover - structural guard
        raise TypeError("cli.main.app did not resolve to a click Group")
    return {
        f"{name}.mdx": _subapp_page(name, cmd)
        for name, cmd in root.commands.items()
        if isinstance(cmd, click.Group)
    }


def _nav_pages() -> set[str]:
    data = json.loads(DOCS_JSON.read_text(encoding="utf-8"))

    pages: set[str] = set()

    def _collect(node: object) -> None:
        if isinstance(node, str):
            pages.add(node)
        elif isinstance(node, list):
            for item in node:
                _collect(item)
        elif isinstance(node, dict):
            for key in ("pages", "groups", "tabs"):
                if key in node:
                    _collect(node[key])

    _collect(data.get("navigation", {}))
    return pages


def _check(generated: dict[str, str]) -> int:
    failures: list[str] = []

    for filename, content in generated.items():
        on_disk = DOCS_CLI_DIR / filename
        if not on_disk.exists():
            failures.append(f"missing generated page: docs/cli/{filename}")
            continue
        current = on_disk.read_text(encoding="utf-8")
        if current != content:
            diff = "\n".join(
                difflib.unified_diff(
                    current.splitlines(),
                    content.splitlines(),
                    fromfile=f"docs/cli/{filename} (committed)",
                    tofile=f"docs/cli/{filename} (regenerated)",
                    lineterm="",
                ),
            )
            failures.append(f"drift in docs/cli/{filename}:\n{diff}")

    expected = {f.removesuffix(".mdx") for f in generated}
    for stale in sorted(DOCS_CLI_DIR.glob("*.mdx")):
        if stale.name in HAND_WRITTEN:
            continue
        if stale.name not in generated:
            failures.append(
                f"stale page docs/cli/{stale.name}: no matching CLI subapp"
                " — remove it or regenerate",
            )

    nav = _nav_pages()
    for slug in sorted({f"cli/{name}" for name in expected} | {"cli/index"}):
        if slug not in nav:
            failures.append(f"docs.json navigation is missing '{slug}'")

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        print(
            f"\n{len(failures)} CLI-reference check failure(s)."
            " Regenerate with: uv run scripts/docs-cli_reference-generate.py",
            file=sys.stderr,
        )
        return 1
    print(f"cli-reference check: {len(generated)} pages in sync.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed pages match a fresh generation (CI drift gate)",
    )
    args = parser.parse_args()

    generated = _generate()
    if args.check:
        return _check(generated)

    DOCS_CLI_DIR.mkdir(parents=True, exist_ok=True)
    for filename, content in generated.items():
        (DOCS_CLI_DIR / filename).write_text(content, encoding="utf-8")
        print(f"wrote docs/cli/{filename}")
    print(f"{len(generated)} pages generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
