from types import SimpleNamespace

from libs.attio import (
    AttioConflictError,
    AttioError,
    AttioValidationError,
    AttributeCreateResult,
    CompanyInput,
    CompanyResult,
    CompanySearchResult,
    ConfigurationError,
    ConnectivityError,
    DeploymentMismatchError,
    ErrorEntry,
    MeetingCandidate,
    MeetingExternalRef,
    MeetingInput,
    MeetingLinkedRecord,
    MeetingParticipantInput,
    MentionInput,
    NoteInput,
    NoteResult,
    PersonInput,
    ReliabilityEnvelope,
    SchemaMismatchError,
    TrackingEventInput,
    WarningEntry,
    assert_attio_token_scopes,
    build_patch_record_request,
    create_attribute,
    create_companies_attribute,
    create_object,
    describe_attio_error,
    ensure_select_options,
    error_envelope,
    fetch_token_scopes as _fetch_token_scopes,
    find_or_create_meeting,
    get_client,
    get_company_values,
    get_person_values,
    is_unknown_filter_attribute,
    iter_meetings_in_range,
    list_attributes,
    list_candidate_meetings,
    list_select_options,
    list_status_options,
    model_dump_or_empty,
    normalize_linkedin_url,
    resolve_owner_member_id,
    resolve_record_id_for_ref,
    search_companies,
    search_people,
    set_company_domain_if_empty,
    update_person,
    upsert_company,
    upsert_person,
)
from libs.caldotcom import (
    BookingAttendee,
    BookingCreatedPayload,
    BookingHost,
    CalcomClient,
    EventType,
    MutationAttendee,
    NoShowAttendee,
    Webhook,
)
from libs.clay_http import post_row
from libs.dlt import (
    CloudGoogle,
    DestinationType,
    GCPCredentials,
    etl_bucket_name,
    raw_bucket_name,
)
from libs.exa import find_companies, find_people
from libs.fathom import iter_meetings, webhook_from_sdk_meeting
from libs.filesystem.files import DestinationFileData, FileUtility, SourceFileData
from libs.fireflies import from_motherduck_row
from libs.gmail import decode_token, extract_id_from_url
from libs.granola import (
    ExportCliJsonPayload,
    ExportRunOptions,
    GranolaError,
    write_meeting_export,
)
from libs.harvest import fetch_profile
from libs.infisical import InfisicalAuthError, InfisicalFetchError, fetch, fetch_all
from libs.linear import client as linear_client
from libs.logging import log, set_source, webhook_request_context
from libs.motherduck import connect, query
from libs.octolens import OctolensClient, Source
from libs.parallel import (
    MatchCondition,
    findall_create,
    findall_result,
    findall_status,
    search,
)
from libs.parsers import normalize_mapping_payload
from libs.rb2b import (
    Payload,
    Webhook as Rb2bWebhook,
    compute_event_id,
    normalize_rb2b_timestamp,
)
from libs.sanity import (
    DEFAULT_API_VERSION,
    DEFAULT_DATASET,
    DEFAULT_PROJECT_ID,
    DuplicateSlugError,
    SanityConfig,
    UnsafeArchiveDirError,
)
from libs.slack import (
    get_client as slack_get_client,
    lookup_user_id_by_email,
    post_message,
)
from libs.telemetry import emit_cli_event, init_log_exporter, init_tracer, span
from libs.webhook import (
    UNSUPPORTED_SLACK_CHANNEL_SECRET,
    WebhookFilter,
    WebhookFilters,
    WebhookModelTypeCheckShim,
)

infisical: SimpleNamespace

fetch_token_scopes = _fetch_token_scopes

__all__ = [
    "DEFAULT_API_VERSION",
    "DEFAULT_DATASET",
    "DEFAULT_PROJECT_ID",
    "UNSUPPORTED_SLACK_CHANNEL_SECRET",
    "AttioConflictError",
    "AttioError",
    "AttioValidationError",
    "AttributeCreateResult",
    "BookingAttendee",
    "BookingCreatedPayload",
    "BookingHost",
    "CalcomClient",
    "CloudGoogle",
    "CompanyInput",
    "CompanyResult",
    "CompanySearchResult",
    "ConfigurationError",
    "ConnectivityError",
    "DeploymentMismatchError",
    "DestinationFileData",
    "DestinationType",
    "DuplicateSlugError",
    "ErrorEntry",
    "EventType",
    "ExportCliJsonPayload",
    "ExportRunOptions",
    "FileUtility",
    "GCPCredentials",
    "GranolaError",
    "InfisicalAuthError",
    "InfisicalFetchError",
    "MatchCondition",
    "MeetingCandidate",
    "MeetingExternalRef",
    "MeetingInput",
    "MeetingLinkedRecord",
    "MeetingParticipantInput",
    "MentionInput",
    "MutationAttendee",
    "NoShowAttendee",
    "NoteInput",
    "NoteResult",
    "OctolensClient",
    "Payload",
    "PersonInput",
    "Rb2bWebhook",
    "ReliabilityEnvelope",
    "SanityConfig",
    "SchemaMismatchError",
    "Source",
    "SourceFileData",
    "TrackingEventInput",
    "UnsafeArchiveDirError",
    "WarningEntry",
    "Webhook",
    "WebhookFilter",
    "WebhookFilters",
    "WebhookModelTypeCheckShim",
    "assert_attio_token_scopes",
    "build_patch_record_request",
    "compute_event_id",
    "connect",
    "create_attribute",
    "create_companies_attribute",
    "create_object",
    "decode_token",
    "describe_attio_error",
    "emit_cli_event",
    "ensure_select_options",
    "error_envelope",
    "etl_bucket_name",
    "extract_id_from_url",
    "fetch",
    "fetch_all",
    "fetch_profile",
    "fetch_token_scopes",
    "find_companies",
    "find_or_create_meeting",
    "find_people",
    "findall_create",
    "findall_result",
    "findall_status",
    "from_motherduck_row",
    "get_client",
    "get_company_values",
    "get_person_values",
    "infisical",
    "init_log_exporter",
    "init_tracer",
    "is_unknown_filter_attribute",
    "iter_meetings",
    "iter_meetings_in_range",
    "linear_client",
    "list_attributes",
    "list_candidate_meetings",
    "list_select_options",
    "list_status_options",
    "log",
    "lookup_user_id_by_email",
    "model_dump_or_empty",
    "normalize_linkedin_url",
    "normalize_mapping_payload",
    "normalize_rb2b_timestamp",
    "post_message",
    "post_row",
    "query",
    "raw_bucket_name",
    "resolve_owner_member_id",
    "resolve_record_id_for_ref",
    "search",
    "search_companies",
    "search_people",
    "set_company_domain_if_empty",
    "set_source",
    "slack_get_client",
    "span",
    "update_person",
    "upsert_company",
    "upsert_person",
    "webhook_from_sdk_meeting",
    "webhook_request_context",
    "write_meeting_export",
]
