name: integration

on:
  schedule:
    - cron: "0 12 * * *" # trunk-ignore(yamllint/quoted-strings)
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  pytest-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv sync --frozen
      - name: Load secrets via Infisical
        uses: Infisical/secrets-action@v1.1.17
        with:
          infisical_token: ${{ secrets.INFISICAL_TOKEN }}
          project_id: ${{ secrets.INFISICAL_PROJECT_ID }}
          environment: dev
      - name: Run integration tests
        run: |
          uv run pytest -m integration --junit-xml=junit.xml -o junit_family=xunit1
        continue-on-error: true
      - name: Upload Test Results to Trunk.io
        if: ${{ always() }}
        continue-on-error: true
        uses: trunk-io/analytics-uploader@95a0fb8b29e45b6068304261fb518644b426a803
        with:
          junit-paths: junit.xml
          org-slug: sanhedrin
          token: ${{ secrets.TRUNK_API_TOKEN }}
