"""Test-first contracts for the uv.lock -> Bazel requirements synchronizer.

`requirements_bazel.txt` is a checked derivative of the authoritative frozen
`uv.lock`, never a second source of dependency truth. These tests pin the
EXPORT_COMMAND argv contract (no weakened hashes, no extras, no credentials, no
shell-string invocation), the atomic generate path (good output survives a uv
failure), and the drift `--check` used by CI.

BD: ai-m4p9.14
"""

from __future__ import annotations

import importlib.util
import shutil
import subprocess
from pathlib import Path

import pytest

# The synchronizer ships under a hyphenated filename (repo convention for
# executable scripts), so it cannot be imported by dotted name. Load it from its
# path so the public contract is unit-testable without going through the CLI.
SCRIPT_PATH = (
    Path(__file__).resolve().parents[2] / "scripts" / "bazel-requirements-sync.py"
)
_spec = importlib.util.spec_from_file_location("bazel_requirements_sync", SCRIPT_PATH)
assert _spec is not None and _spec.loader is not None
sync = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sync)

REPO_ROOT = sync.REPO_ROOT
HAS_UV = shutil.which("uv") is not None
uv_required = pytest.mark.skipif(not HAS_UV, reason="uv not on PATH")


@pytest.fixture(scope="module")
def projection() -> str:
    """The exact projection uv emits for the frozen lock, computed once."""
    return sync.render_projection(REPO_ROOT)


def test_export_command_is_an_argv_list() -> None:
    # A list (never a shell string) is the contract: subprocess.run gets argv,
    # never `shell=True`, so no shell injection and no quoting drift.
    assert isinstance(sync.EXPORT_COMMAND, list)
    assert all(isinstance(part, str) for part in sync.EXPORT_COMMAND)
    assert sync.EXPORT_COMMAND[0] == "uv"


def test_export_command_projects_frozen_lock_without_project_root() -> None:
    # Frozen only (no stale pyproject drift), hashed third-party wheels only
    # (the project root is built by Bazel, never pip-installed).
    assert "--frozen" in sync.EXPORT_COMMAND
    assert "--no-emit-project" in sync.EXPORT_COMMAND


@pytest.mark.parametrize(
    "forbidden",
    [
        "--no-hashes",
        "--all-extras",
        "--extra",
        "--index-url",
        "--extra-index-url",
        "--find-links",
        "--index-strategy",
        "--keyring-provider",
        "--default-index",
        "--client-cert",
    ],
)
def test_export_command_has_no_weakening_or_credential_flags(forbidden: str) -> None:
    assert forbidden not in sync.EXPORT_COMMAND


@uv_required
def test_render_projection_matches_a_direct_uv_export(projection: str) -> None:
    # The synchronizer must not massage uv's output: the projection is byte-for-byte
    # what `uv export` prints, header included, so the committed file is reproducible.
    direct = subprocess.run(
        [*sync.EXPORT_COMMAND],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    assert sync.render_projection(REPO_ROOT) == direct == projection


@uv_required
def test_render_projection_is_hashed_and_excludes_project_root(
    projection: str,
) -> None:
    # Every pinned wheel carries a hash; the project itself is never emitted.
    assert "--hash=sha256:" in projection
    assert "-e ." not in projection
    lines = [ln for ln in projection.splitlines() if ln and not ln.startswith("#")]
    assert lines, "projection must contain pinned requirements"
    header = projection.splitlines()[0]
    assert header.startswith("# This file was autogenerated by uv")


@uv_required
def test_generate_writes_the_exact_projection_atomically(
    tmp_path: Path,
    projection: str,
) -> None:
    out = tmp_path / "requirements_bazel.txt"
    sync.generate(output=out, repo_root=REPO_ROOT)
    assert out.read_text() == projection


@uv_required
def test_generate_preserves_good_output_when_uv_fails(tmp_path: Path) -> None:
    # A frozen export from a directory with no lock must fail. The previously
    # committed good file has to survive untouched -- a half-written or empty
    # requirements file would break every downstream Bazel target.
    empty_repo = tmp_path / "empty"
    empty_repo.mkdir()
    out = tmp_path / "requirements_bazel.txt"
    sentinel = "# previously committed good projection\n"
    out.write_text(sentinel)

    with pytest.raises(Exception):
        sync.generate(output=out, repo_root=empty_repo)

    assert out.read_text() == sentinel


@uv_required
def test_check_reports_in_sync_when_file_matches_projection(
    tmp_path: Path,
    projection: str,
) -> None:
    out = tmp_path / "requirements_bazel.txt"
    out.write_text(projection)
    assert sync.is_in_sync(output=out, repo_root=REPO_ROOT) is True


@uv_required
def test_check_reports_drift_when_file_diverges(
    tmp_path: Path,
    projection: str,
) -> None:
    out = tmp_path / "requirements_bazel.txt"
    out.write_text(projection + "\n# stale hand edit\n")
    assert sync.is_in_sync(output=out, repo_root=REPO_ROOT) is False


@uv_required
def test_check_reports_drift_when_file_missing(tmp_path: Path) -> None:
    out = tmp_path / "requirements_bazel.txt"
    assert sync.is_in_sync(output=out, repo_root=REPO_ROOT) is False


@uv_required
def test_cli_check_exits_nonzero_on_drift(tmp_path: Path, projection: str) -> None:
    import typer

    out = tmp_path / "requirements_bazel.txt"
    out.write_text(projection + "\n# drift\n")
    with pytest.raises(typer.Exit) as exc:
        sync.main(check=True, output=out, repo_root=REPO_ROOT)
    assert exc.value.exit_code == 1


@uv_required
def test_cli_check_exits_zero_when_in_sync(tmp_path: Path, projection: str) -> None:
    out = tmp_path / "requirements_bazel.txt"
    out.write_text(projection)
    sync.main(check=True, output=out, repo_root=REPO_ROOT)  # must not raise
